### ISSUE TITLE
Deno/Typescript example doesn't work

### ISSUE THREAD

**Issue by dgrisham** [shimataro/node-adjuster#528]
Deno version: 1.5.2 (using the `hayd/deno:1.5.2` dockerfile)
`value-schema` version: 3.0.0, imported from `https://deno.land/x/value_schema/mod.ts`.

```
interface Parameters {
    foo: number;
    bar: string;
}

const schemaObject = {
    foo: vs.number(),
    bar: vs.string(),
};
const input = {
    foo: "12345",
    bar: "abcde",
};

const actual = vs.applySchemaObject<Parameters>(schemaObject, input);
```

Compiling with this code gives the error:

```
error: TS2344 [ERROR]: Type 'Parameters' does not satisfy the constraint 'Record<string, BaseSchema<unknown>>'.
  Index signature is missing in type 'Parameters'.
const actual = vs.applySchemaObject<Parameters>(schemaObject, input);
```

To solve this, I imported `BaseSchema` from `https://deno.land/x/value_schema@v3.0.0/dist-deno/schemaClasses/BaseSchema.ts` and updated my code to include an index in the `Parameters` interface:

```
interface Parameters {
    foo: number;
    bar: string;
    [key: string]: BaseSchema<unknown>
}

const schemaObject = {
    foo: vs.number(),
    bar: vs.string(),
};
const input = {
    foo: "12345",
    bar: "abcde",
};

const actual = vs.applySchemaObject<Parameters>(schemaObject, input);
```
 
This updated resulted in the following build errors:

```
error: TS2411 [ERROR]: Property 'foo' of type 'number' is not assignable to string index type 'BaseSchema<unknown>'.
    foo: number;
    ~~~
    at file:///home/dev/reports/index.ts:12:5

TS2411 [ERROR]: Property 'bar' of type 'string' is not assignable to string index type 'BaseSchema<unknown>'.
    bar: string;
    ~~~
    at file:///home/dev/reports/index.ts:13:5

TS2345 [ERROR]: Argument of type '{ foo: NumberSchema<never>; bar: StringSchema<never>; }' is not assignable to parameter of type 'Parameters'.
  Types of property 'foo' are incompatible.
    Type 'NumberSchema<never>' is not assignable to type 'number'.
const actual = vs.applySchemaObject<Parameters>(schemaObject, input);
                                                ~~~~~~~~~~~~
    at file:///home/dev/reports/index.ts:26:49

Found 3 errors.
```

Finally, I imported the `NumberSchema` and `StringSchema` types in an attempt to fully satisfy the typechecker. The final code was:

```
interface Parameters {
    foo: NumberSchema;
    bar: StringSchema;
    [key: string]: BaseSchema<unknown>
}

const schemaObject = {
    foo: vs.number(),
    bar: vs.string(),
};
const input = {
    foo: "12345",
    bar: "abcde",
};

const actual = vs.applySchemaObject<Parameters>(schemaObject, input);
```

This works, but I'd rather not have to specify the `NumberSchema`, `StringSchema`, and `BaseSchema` types at all, as per the example on the README. Is there a simpler update I can do to make this work with the interface without importing all of those types?

Let me know if I can provide any more info, thanks!

**Comment by shimataro** [comment]
Hi, @dgrisham 
You don't need to use `<Parameter>`.
Just write as below:

```typescript
import vs from "https://deno.land/x/value_schema/mod.ts";

const schemaObject = {
    foo: vs.number(),
    bar: vs.string(),
};
const input = {
    foo: "12345",
    bar: "abcde",
};

const actual = vs.applySchemaObject(schemaObject, input);

// { foo: 12345, bar: "abcde" }
console.log(actual);
```

(example code in README is old, I will fix it later)

thanks!

**Comment by shimataro** [comment]
@dgrisham 
Did you solve the problem? Can I close this issue?

**Comment by dgrisham** [comment]
Hey! Sorry for not following up. We ended up abandoning typescript after some experimentation. To the best of my memory right now, I think the solution you offered sacrificed compiler-time type checks that we'd wanted to retain.

**Comment by shimataro** [comment]
Hi, @dgrisham 

>  I think the solution you offered sacrificed compiler-time type checks that we'd wanted to retain.

No, type checking works perfectly!

- - -

completion on IntelliJ IDEA:

![image](https://user-images.githubusercontent.com/3448502/107706214-4bdc7280-6d03-11eb-982c-79a04bca3cee.png)
![image](https://user-images.githubusercontent.com/3448502/107706475-b7264480-6d03-11eb-9413-2e4188b892b7.png)
![image](https://user-images.githubusercontent.com/3448502/107706538-d3c27c80-6d03-11eb-9761-7bf1f3e19345.png)

- - -

runtime type checking:

![image](https://user-images.githubusercontent.com/3448502/107706798-37e54080-6d04-11eb-82f6-c3683e4b7e93.png)
![image](https://user-images.githubusercontent.com/3448502/107706892-5d724a00-6d04-11eb-92aa-b23b95a1ffad.png)
